### ISSUE TITLE
Error loading tokenizer

### ISSUE THREAD

**Issue by AsyaOrlova** [HelloJocelynLu/t5chem#24]
When I load tokenizer from a pre-trained USPTO-MT model

`tokenizer = SimpleTokenizer(vocab_file='models/USPTO_500_MT/vocab.pt')`

I get an error: 

Traceback (most recent call last):
  File "/mnt/tank/scratch/aorlova/t5_chem_eval/t5_chem_eval.py", line 11, in <module>
    tokenizer = SimpleTokenizer(vocab_file='models/USPTO_500_MT/vocab.pt')
  File "/nfs/home/aorlova/anaconda3/envs/t5env/lib/python3.10/site-packages/t5chem/mol_tokenizers.py", line 204, in __init__
    super().__init__(vocab_file=vocab_file, max_size=max_size, **kwargs)
  File "/nfs/home/aorlova/anaconda3/envs/t5env/lib/python3.10/site-packages/t5chem/mol_tokenizers.py", line 75, in __init__
    self.create_vocab(vocab_file=vocab_file)
  File "/nfs/home/aorlova/anaconda3/envs/t5env/lib/python3.10/site-packages/t5chem/mol_tokenizers.py", line 101, in create_vocab
    self.vocab: Vocab = Vocab.load(vocab_file)
  File "/nfs/home/aorlova/anaconda3/envs/t5env/lib/python3.10/site-packages/t5chem/mol_tokenizers.py", line 51, in load
    tokens = [line.strip() for line in f]
  File "/nfs/home/aorlova/anaconda3/envs/t5env/lib/python3.10/site-packages/t5chem/mol_tokenizers.py", line 51, in <listcomp>
    tokens = [line.strip() for line in f]
  File "/nfs/home/aorlova/anaconda3/envs/t5env/lib/python3.10/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 64: invalid start byte

**Comment by HelloJocelynLu** [comment]
Hi,

Thank you for bringing this. I have recently updated the codebase, and as a result, the previous version of `vocab.pt` is no longer compatible with the latest code.

For a temporary workaround, please refer to this GitHub issue: https://github.com/HelloJocelynLu/t5chem/issues/23

Please let me know if this addresses your concern or if you need any further assistance.

--------------------
Update:
I've also updated the downloading url in README.rst. Downloading the new model weights should resolve this issue.

Best regards,
Jocelyn

**Comment by AsyaOrlova** [comment]
Thank you for the quick answer, this solved my problem!
